The angle is **positive** when one of the following is true:

$X → Y$

$Y → Z$

$Z → X$

The angle is **negative** when one of the following is true:

$Y → X$

$Z → Y$

$X → Z$

In [1]:
# Initial frame
# z is pointing outward
# y is pointing down
# x is pointing left

# Target frame
# z is pointing left
# y is pointing inward
# x is pointing up

In [18]:
# Rotation Z-axis
import numpy as np
import math
theta_z = - np.pi/2

# yaw = Rotation_z_axis
Rotation_z_axis = np.array([[math.cos(theta_z), - math.sin(theta_z), 0],
                            [math.sin(theta_z),   math.cos(theta_z), 0],
                            [0,                        0           , 1]])
print(np.around(Rotation_z_axis))

[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]


In [3]:
# Rotation Y-axis
import numpy as np
import math
theta_y = 0

# pitch = Rotation_y_axis
Rotation_y_axis = np.array([[math.cos(theta_y),  0, math.sin(theta_y)],
                            [0,                  1,                 0],
                            [-math.sin(theta_y), 0, math.cos(theta_y)]])
print(np.around(Rotation_y_axis))

[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]


In [19]:
# Rotation X-axis
import numpy as np
import math
theta_x = - np.pi/2

# roll = Rotation_x_axis
Rotation_x_axis = np.array([[1,                 0,                  0],
                            [0, math.cos(theta_x), -math.sin(theta_x)],
                            [0, math.sin(theta_x), math.cos(theta_x)]])
print(np.around(Rotation_x_axis))

[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0. -1.  0.]]


In [20]:
# 3D coordinate from target frame

orig_coord = np.array([[21],
                       [2.5],
                       [0.9]])

# First rotate along the x axis
target_coord = np.matmul(Rotation_x_axis, orig_coord)
# print(np.around(target_coord, decimals=2))

# Second rotate along the y axis
target_coord = np.matmul(Rotation_y_axis, target_coord)
# print(np.around(target_coord, decimals=2))

target_coord = np.matmul(Rotation_x_axis, np.matmul(Rotation_y_axis, np.matmul(Rotation_z_axis, orig_coord)))
target_coord = np.matmul(Rotation_x_axis, np.matmul(Rotation_y_axis, Rotation_z_axis))

print("Rotation_z_axis")
print(np.around(Rotation_z_axis))
print("Rotation_x_axis")
print(np.around(Rotation_x_axis))
print("trans_matrix")
trans_matrix = np.matmul(Rotation_x_axis, Rotation_z_axis)
print(np.around(trans_matrix))

Rotation_z_axis
[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
Rotation_x_axis
[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0. -1.  0.]]
trans_matrix
[[ 0.  1.  0.]
 [-0.  0.  1.]
 [ 1. -0.  0.]]


In [15]:
A = np.array([[1, 2],
              [2, 1]])
B = np.array([[3, 4],
              [3, 4]])

print(np.matmul(A, B))


theta = - np.pi/2

C_C = np.array([[math.cos(theta), -math.sin(theta)],
                [math.sin(theta), math.cos(theta)]])
print("C_C")
print(np.around(C_C))
theta_2 = np.pi/2
C = np.array([[math.cos(theta_2), math.sin(theta_2)],
            [-math.sin(theta_2), math.cos(theta_2)]])
print("C")
print(np.around(C))

[[ 9 12]
 [ 9 12]]
C_C
[[ 0.  1.]
 [-1.  0.]]
C
[[ 0.  1.]
 [-1.  0.]]
